common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  username: root
  password: RathanakPassword

development:
  <<: *common
  database: khmer_zone_develop

test:
  <<: *common
  database: khmer_zone_test

staging:
  <<: *common
  database: khmer_zone_staging

production:
  <<: *common
  database: khmer_zone_production
